WebUI2/Controllers/AdminController.cs
using Model;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebUI2.Models;

namespace WebUI2.Controllers
{

    /// <summary>
    /// Provides functionality required for the administration of the products catalogue
    /// and addition or deletion of registered users
    /// </summary>

    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private IRepository repo;
        private const int pageSize = 10;

        public AdminController(IRepository repo)
        {
            this.repo = repo;          
        }



        public ViewResult Index(int page = 1)
        {
            PagingInfo pageInf = new PagingInfo
            {
                    PageSize = pageSize,
                    Products = repo.Products
                    .OrderBy(p => p.ProductID)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                    TotalItems = repo.Products.Count(),
                    CurrentPage = page
            };
            return View(pageInf);
        }


        public ViewResult Edit(int ProductID, int page = 1)
        {
            Product product = repo.Products.FirstOrDefault(p => p.ProductID == ProductID);
            ProductInfo prInf = new ProductInfo
            {
                CurrentPage = page,
                Product = product,
                SizeHolders = repo.Sizes.Select(p => p.Value).ToArray(),
                ColorHolders = repo.Colors.Select(p => p.Value).ToArray()
            };
                 
            return View(prInf);
        }




        [HttpPost]
        public ViewResult Edit(ProductInfo prInf, HttpPostedFileBase image, int page = 1)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    prInf.Product.ImageMimeType = image.ContentType;
                    prInf.Product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(prInf.Product.ImageData, 0, image.ContentLength);
                }
                AddSizes(prInf.SizeHolders, ref prInf);
                AddColors(prInf.ColorHolders, ref prInf);
                repo.SaveProduct(prInf.Product);
                TempData["Confirm"] = $"{prInf.Product.Name} has been saved";
               
                return View("Index", new PagingInfo
                {
                    PageSize = pageSize,
                    Products = repo.Products
                    .OrderBy(p => p.ProductID)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                    TotalItems = repo.Products.Count(),
                    CurrentPage = page
                }
                          );
            }
            else
            {
                // validation hasn't succeeded - return to the edit view
                return View(prInf);
            }

        }

        private void AddColors(string[] colorHolders, ref ProductInfo prInf)
        {
            if (colorHolders != null)
            {
                foreach (var color in colorHolders)
                {
                    //add color
                    prInf.Product.ProductToColors.Add(
                                   new ProductToColor
                                   {
                                       ColorId = repo.Colors.First(p => p.Value == color).ColorId,
                                       ProductID = prInf.Product.ProductID
                                   });
                }
            }
        }




        private void AddSizes(string[] sizeHolders, ref ProductInfo prInf)
        {
            if (sizeHolders != null)
            {
                foreach (var size in sizeHolders)
                {
                    //add sizes
                    prInf.Product.ProductToSizes.Add(
                                   new ProductToSize
                                   {
                                       SizeId = repo.Sizes.First(p => p.Value == size).Id,
                                       ProductID = prInf.Product.ProductID
                                   });
                }

            }
        }





        [HttpPost]
        public ActionResult Delete(int ProductID)
        {
            Product product = repo.Products.FirstOrDefault(p => p.ProductID == ProductID);

            if (repo.DeleteProduct(product))
            {
                TempData["Confirmation"] = $"{product.Name} has been deleted";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Fail"] = "Failed to delete product";
                return RedirectToAction("Index");
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }



        public void InsertCountries()
        {

            string[] countries = {"Country Name","Afghanistan","Akrotiri","Albania", "Algeria", "American Samoa",
           "Andorra", "Angola","Anguilla","Antarctica", "Antigua and Barbuda","Argentina","Armenia", "Aruba",
           "Ashmore and Cartier Islands","Australia","Austria","Azerbaijan","Bahamas", "Bahrain", "Bangladesh", 
           "Barbados","Bassas da India","Belarus","Belgium","Belize", "Benin", "Bermuda", "Bhutan",
"Bolivia","Bosnia and Herzegovina", "Botswana", "Bouvet Island","Brazil","British Indian Ocean Territory",
"British Virgin Islands","Brunei","Bulgaria", "Burkina Faso","Burma","Burundi","Cambodia","Cameroon","Canada",
"Cape Verde","Cayman Islands","Central African Republic","Chad","Chile","China","Christmas Island",
"Clipperton Island","Cocos (Keeling) Islands","Colombia","Comoros", "Democratic Republic of Congo",
"Republic of the Cook Islands","Coral Sea Islands","Costa Rica","Cote d Ivoire","Croatia","Cuba",
"Cyprus","Czech Republic","Denmark","Dhekelia","Djibouti","Dominica","Dominican Republic","Ecuador",
"Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Ethiopia","Europa Island","Falkland Islands (Islas Malvinas)",
"Faroe Islands","Fiji","Finland","France","French Guiana","French Polynesia","French Southern and Antarctic Lands",
"Gabon","Gambia","The Gaza Strip","Georgia","Germany","Ghana","Gibraltar","Glorioso Islands","Greece",
"Greenland","Grenada","Guadeloupe","Guam","Guatemala","Guernsey","Guinea","Guinea-Bissau","Guyana",
"Haiti","Heard Island and McDonald Islands","Holy See (Vatican City)","Honduras","Hong Kong","Hungary",
"Iceland","India","Indonesia","Iran","Iraq","Ireland","Isle of Man","Israel","Italy","Jamaica",
"Jan Mayen","Japan","Jersey","Jordan","Juan de Nova Island","Kazakhstan","Kenya","Kiribati","Korea North",
"Korea South","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein",
"Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali",
"Malta","Marshall Islands","Martinique","Mauritania","Mauritius","Mayotte","Mexico","Federated States of Micronesia",
"Moldova","Monaco","Mongolia","Montserrat","Morocco","Mozambique","Namibia","Nauru","Navassa Island",
"Nepal","Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger",
"Nigeria","Niue","Norfolk Island","Northern Mariana Islands","Norway","Oman","Pakistan","Palau",
"Panama","Papua New Guinea","Paracel Islands","Paraguay","Peru","Philippines","Pitcairn Islands",
"Poland","Portugal","Puerto Rico","Qatar","Reunion","Romania","Russia","Rwanda","Saint Helena",
"Saint Kitts and Nevis","Saint Lucia","Saint Pierre and Miquelon","Saint Vincent and the Grenadines",
"Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia and Montenegro",
"Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands","Somalia",
"South Africa","South Georgia and the South Sandwich Islands","Spain","Spratly Islands","Sri Lanka",
"Sudan","Suriname","Svalbard","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan",
"Tanzania","Thailand","Timor-Leste","Togo","Tokelau","Tonga","Trinidad and Tobago","Tromelin Island",
"Tunisia","Turkey","Turkmenistan","Turks and Caicos Islands","Tuvalu","Uganda","Ukraine",
"United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Vanuatu","Venezuela",
"Vietnam","Virgin Islands","Wake Island","Wallis and Futuna","West Bank","Western Sahara","Yemen",
"Zambia","Zimbabwe"};



            TeethStoreEntities database = new TeethStoreEntities();

            foreach (String country in countries)
            {
                database.Countries.Add(new Country { Name = country });
            }
            database.SaveChanges();
        }



        public ActionResult UploadBackgroundImage(HttpPostedFileBase image) 
        {

            if (image != null)
            {
                BackgroundImage im = new BackgroundImage
                {
                    ImageMimeType = image.ContentType,
                    ImageData = new byte[image.ContentLength]
                };
                image.InputStream.Read(im.ImageData, 0, image.ContentLength);


                repo.SaveBckgr(im);
                TempData["Confirm"] = "The image has been saved";
            }
            else 
                TempData["Fail"] = "Failed to save image";
            
                
            return View("Index", new PagingInfo
              {
                 PageSize = pageSize,
                 Products = repo.Products
                 .OrderBy(p => p.ProductID)
                 .Take(pageSize),
                 TotalItems = repo.Products.Count()
              }
              );
            
        }





    }
}

WebUI2/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using WebUI2.Models;
using System.Configuration;
using System.Data.SqlClient;
using WebUI2.Binders;
using Model.Entities;
using Model.ExternalAuthentication;
using System.Threading.Tasks;
using Model.EF;
using System.Net.Http;
using System.Net;
using System.Web.Helpers;
using Newtonsoft.Json.Linq;
using System.Collections;





namespace WebUI2.Controllers
{


    /// <summary>
    /// Contains business logic necessary to display, update and manage products information to the user.
    /// Also processes products search requests
    /// </summary>
    public class ProductsController : Controller
    {
        private IRepository repository;
        public int pageSize = 4;


        public ProductsController(IRepository repository)
        {
            this.repository = repository;
        }



        /// <summary>
        /// retrieves products data from the database and sends all necessary info for display to the view
        /// </summary>
        public ViewResult List(string currentCategory, string currentSubCategory)
        {
            IQueryable<Product> products = (repository.Products)
                                 .Where(p => currentCategory == null || p.Category == currentCategory)
                                 .Where(p => currentSubCategory == null || p.SubCategory == currentSubCategory)
                                 .OrderBy(p => p.ProductID)
                                 .Take(pageSize);

            PagingInfo info = new PagingInfo
            {
                Products = (IEnumerable<Product>)products,
                PageSize = pageSize,
                Category = currentCategory,
                SubCategory = currentSubCategory
            };
            return View(info);
        }








        public ActionResult AjaxList(string currentCategory, string subCategory, int skipSize, int addSize = 0)
        {
            IQueryable<Product> products = (repository.Products)
                                 .Where(p => currentCategory == "" || p.Category == currentCategory)
                                 .Where(p => subCategory == "" || p.SubCategory == subCategory)
                                 .OrderBy(p => p.ProductID)
                                 .Skip(skipSize)
                                 .Take(addSize);



            return PartialView("_ProductsBundle", products);
        }





        public FileContentResult GetImage(int productId)
        {
            Product product = repository.Products.First(p => p.ProductID == productId);
            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }



        public ViewResult ShowDetailedDescription(int productId, string returnUrl)
        {
            if (returnUrl.Contains("/Products/AjaxList"))
            {
                returnUrl = "/Products/List";
            }

            ViewData["returnUrl"] = returnUrl;
            Product product = repository.Products.First(p => p.ProductID == productId);

            // create an instance of the recently viewed class  - to store the products viewed
            RecentlyViewed recentViews =
                (RecentlyViewed)(new RecentViewsModelBinder()).BindModel(this.ControllerContext, new ModelBindingContext());


            // make sure only one instance of each product is added to the view
            if (!recentViews.ContainsProduct(product))
            {
                recentViews.AddRecentProduct(product);
            }
            else
            {
                recentViews.AddProductAndMove(product);
            }

            IEnumerable<int> sizeIds = product.ProductToSizes.Select(p => p.SizeId);
            IEnumerable<int> colorIds = product.ProductToColors.Select(p => p.ColorId);

            ProductInfo inf = new ProductInfo {
                                                 SizeHolders = repository.
                                                 Sizes.Where(p => sizeIds.Contains(p.Id)).
                                                 Select(d => d.Value).ToArray(),
                                                 Product = product,
                                                 ColorHolders = repository.
                                                 Colors.Where(p => colorIds.Contains(p.ColorId)).
                                                 Select(d => d.Value).ToArray()
                                              };
            return View(inf);
        }





        public ActionResult SearchDatabase(string searchWord)
        {
            SearchData data = new SearchData();
            data.Results = repository.GetSearchResults(searchWord);
            return PartialView("_SearchResults", data.Results);
        }



        [HttpGet]
        public JsonResult AddFavourite(int productId)
        {
            ApplicationUser user = (ApplicationUser)Session["Profile"];


            if (repository.AddFavourite(user.UserName, productId))
            {
                Session["Profile"] = repository.FindByName(user.UserName);
                var jsonData = new AddFavModel { Result = "success", UserName = user.UserName };
                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var jsonData = new AddFavModel { Result = "fail", UserName = user.UserName };
                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
        }//


        public ViewResult WishList(string UserName, string returnUrl = "/Products/List") 
        {  
           ApplicationUser user = repository.FindByName(UserName);
           IEnumerable<FavouriteItem> wishList = user.FavouritesList.Select(p => p);
           ViewBag.Data = returnUrl; 
           return View(wishList);
        }


        [HttpGet]
        public PartialViewResult GetWishListString()
        {
            ApplicationUser user = (ApplicationUser)Session["Profile"];
            IEnumerable<FavouriteItem> wishList = user.FavouritesList.Select(p => p);
            ViewBag.returnUrl = "/Account/Personal";
     
            return PartialView("_WishListInner", wishList);
        }



        public ViewResult DeleteFromWishList(string userName, int productId) 
        {
            repository.RemoveFavourite(userName, productId);
            IEnumerable<FavouriteItem> wishList = repository.FindByName(userName).FavouritesList.Select(p => p);
            Session["Profile"] = repository.FindByName(userName);
            ViewBag.Data = "/Products/List";
            return View("WishList", wishList);
        }


        public String GetProdName(int productId) 
        {
            return repository.Products.Where(p => p.ProductID == productId).First().Name;
        }

    }
}

WebUI2/Views/Admin/Delete.cshtml
@model Model.EF.Product



<h2>Delete</h2>

WebUI2/Views/Admin/Edit.cshtml
@model WebUI2.Models.ProductInfo



<div class="validation-fail">
    @Html.ValidationSummary()
</div>


@{
    string str = Model.Product.Name ?? "Use the form below to create a new product";
    <h2>@str</h2>
}

<hr />

@using (Html.BeginForm("Edit", "Admin", new { page = Model.CurrentPage }, FormMethod.Post, new { enctype = "multipart/form-data", defaultbutton = "submitbutton" }))
{
    <div class="product-editor">

        @Html.HiddenFor(p => p.Product.ProductID)
        <br />
        @Html.Label("Name")
        @Html.EditorFor(p => p.Product.Name)
        <br />
        <br />
        @Html.Label("Description")

        @Html.EditorFor(p => p.Product.Description)
        <br />
        <br />
        @Html.Label("Category")

        @Html.EditorFor(p => p.Product.Category)
        <br />
        <br />
        @Html.Label("SubCategory")

        @Html.EditorFor(p => p.Product.SubCategory)
        <br />
        <br />
        @Html.Label("Price")

        @Html.EditorFor(p => p.Product.Price)
        <br />
        <br />
        @Html.Label("Long Description")
        @Html.EditorFor(p => p.Product.LongDescription)
        <br />
        <br />
        @Html.Label("Source Url")
        @Html.EditorFor(p => p.Product.ExternalLink)
        <br />
        <br />

        <h2>Image</h2>

        <table>
            <tr>
                <td>
                    <img class="view-summary-image" src="@Url.Action("GetImage", "Products", new{ productId=Model.Product.ProductID })" />         
                </td>
                <td>
                    Upload New Image
                    <br />
                    <input type="file" name="Image" />
                </td>
            </tr>
        </table>

        <br />
        <br />

        <hr />

        <table>
            <tr>
                <td>
                    Select sizes available <br />
                    (Hold CTRL button to select multiple values)
                    <br />
                    @Html.ListBoxFor(p => p.SizeHolders, new SelectList(
                                         Model.SizeHolders))
                </td>
                <td>
                    Select colors available <br />
                    (Hold CTRL button to select multiple values)
                    <br />
                    @Html.ListBoxFor(p => p.ColorHolders, new SelectList(
                                         Model.ColorHolders))
                </td>
            </tr>
        </table>
        <p>
            <input type="submit" id="submitbutton" value="Submit Changes" />
        </p>
        <p>
            @Html.ActionLink("Cancel and Return to List", "Index")
        </p>
    </div>


}

WebUI2/Views/Admin/Index.cshtml
@model WebUI2.Models.PagingInfo
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin Page</h2>


<br />
<p>
    @Html.ActionLink("Add a new product", "Create")
</p>
<br />


<table cellspacing="20">

    <tr>
        <th>
            Photo
        </th>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th class="colRight"></th>
    </tr>


    @foreach (var p in Model.Products)
    {
        <tr>
            <td>
                <img class="view-summary-image" src="@Url.Action("GetImage", "Products", new { productId=p.ProductID })" />
            </td>
            <td>
                @p.ProductID
            </td>
            <td>
                @Html.ActionLink(p.Name, "Edit", new { ProductID = p.ProductID, page = Model.CurrentPage })
            </td>

            <td>
                @p.Price.ToString("c")
            </td>
            <td>
                @using (Html.BeginForm("Delete", "Admin"))
                {
                    @Html.Hidden("ProductID", p.ProductID)
                    <input type="submit" value="Delete" />
                }

            </td>
        </tr>
    }
</table>

@for (int i = 0; i <= (Model.TotalItems / Model.PageSize); i++)
{
    string cssClass = Model.CurrentPage == (i + 1) ? "current-page" : "";
    
    @Html.ActionLink(Convert.ToString(i + 1), "Index", new { page = (i + 1) }, new { @class= cssClass}); @:&nbsp;&nbsp;
}

<br />
<br />
<br />

<p>
    @Html.ActionLink("Add a new product", "Create")
</p>








<hr />
@using (Html.BeginForm("DeleteUser", "Admin"))
{

    <legend>Delete a user</legend>

    <br />
    @Html.Label("Username") @Html.TextBox("username")
    <br />

    <input type="submit" value="Delete" />

}



<br />
<br />
<hr />

@Html.ActionLink("Insert countries names into database", "InsertCountries", "Admin")



<br />
<br />
<hr />
@using (Html.BeginForm("UploadBackgroundImage", "Admin", FormMethod.Post, new { enctype="multipart/form-data" })) 
{
    @:Select the background image to upload
    <input type="file" value="browse" name="image" />
    <input type="submit" value="Submit" />
}