WebUI2/Controllers/CartController.cs
using Model;
using Model.Abstracts;
using Model.EF;
using Model.Entities;
using Model.ExternalAuthentication;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebUI2.Models;
using WebUI2.SearchAddress;




namespace WebUI2.Controllers
{

    /// <summary>
    /// Processes all user actions related to their cart and items placed in the cart.
    /// Prepares data necessary for checkout and performs address and model validation
    /// </summary>
    public class CartController : Controller
    {
        IRepository repo;
        IPaymentProcessor paymentProcessor;
        IMailProcessor mailSender;



        public CartController(IRepository repo, IPaymentProcessor paymentProcessor, IMailProcessor mailSender)
        {
            this.repo = repo;
            this.paymentProcessor = paymentProcessor;
            this.mailSender = mailSender;
        }




        // we get the cart object from the cartModelBinder
        public String AddItemAjax(ShoppingCart cart, int productId, string returnUrl, string returnUrl2, string size, string color)
        {
            Product product = repo.Products.FirstOrDefault(p => p.ProductID == productId);
            product.SelectedSize =( size ?? repo.Sizes.First().Value);
            product.SelectedColour = (color ?? repo.Colors.First().Value);
            cart.AddItem(product);
            string str = "Your Cart:  " + cart.ProductLines.Sum(x => x.Quantity) + " item(s): " +
            cart.ComputeCartValue().ToString("c");

            return str;
        }




        public RedirectResult AddItem(ShoppingCart cart, int productId, string returnUrl, string returnUrl2)
        {
            Product product = repo.Products.Where(p => p.ProductID == productId).FirstOrDefault();
            cart.AddItem(product);

            if (returnUrl != null)
            { return Redirect(returnUrl); }

            else
            { return Redirect(returnUrl2); }
        }



        public RedirectToRouteResult RemoveItem(ShoppingCart cart, int productId, string returnUrl)
        {
            Product product = repo.Products.Where(p => p.ProductID == productId).FirstOrDefault();
            cart.RemoveItem(product);

            return RedirectToAction("Index", new { returnUrl });
        }


        public ViewResult Index(ShoppingCart cart, string returnUrl)
        {
            CartInfo cartInfo = new CartInfo();
            cartInfo.Cart = cart;
            cartInfo.ReturnUrl = returnUrl;
            return View(cartInfo);
        }

        public PartialViewResult CartSummary(ShoppingCart cart)
        {
            return PartialView(cart);
        }





        public ViewResult Checkout(ShoppingCart cart)
        {
            string countryName = RegionInfo.CurrentRegion.DisplayName;

            if (cart.ProductLines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your cart is empty");
            }

            if (ModelState.IsValid)
            {
                // this message will be used by popup dialog window
                ViewData["message"] = "Would you like to update your details?";
                // user is logged in - use their details
                if (Session["Profile"] != null)
                {
                    // initialize objects to be passed to the view
                    ShippingInfo shipInfo = InitializeModel(repo);
                    return View(shipInfo);
                }
                else
                {   // if the user is not registered return a blank class
                    return View(new ShippingInfo(repo) { ShipDet = new ShippingDetails { Country = countryName } });
                }
                

            }
            else
            {
                CartInfo inf = new CartInfo
                {
                    Cart = cart,
                    ReturnUrl = "/"
                };
                return View("Index", inf);
            }
        }





        private ShippingInfo InitializeModel(IRepository repo)
        {

            ApplicationUser prof = (ApplicationUser)Session["Profile"];

            ShippingInfo shipInfo = new ShippingInfo(repo)
            {
                ShipDet = new ShippingDetails()
                {
                    Name = prof.Name,
                    Surname = prof.Surname,
                    Email = prof.Email,
                    Phone = prof.Phone
                }
            };


            if (prof.ShippingAddressId != null)
            {
                ShippingAddress adr = prof.ShippingAddress.Where(p => p.RecordId == prof.ShippingAddressId).First();
                // if address data is present fill the model

                shipInfo.ShipDet.UnitFlat = adr.UnitNumber;
                shipInfo.ShipDet.Town = adr.Town;
                shipInfo.ShipDet.StreetType = adr.StreetType;
                shipInfo.ShipDet.StreetNumber = adr.StreetNumber;
                shipInfo.ShipDet.StreetName = adr.StreetName;
                shipInfo.ShipDet.State = adr.State;
                shipInfo.ShipDet.PostCode = adr.PostCode;
                shipInfo.ShipDet.Country = adr.Country;
            }

            return shipInfo;
        }





        [HttpPost]
        public ViewResult ProceedToPay(ShoppingCart cart, ShippingDetails ShipDet, string updateUser)
        {
            
            if (ModelState.IsValid)
            {
                CartShipPayInfo cspInfo = new CartShipPayInfo();
                // prepare for credit card payment
                PrepareCreditCardFields();

                if (updateUser == null ? false : updateUser.Equals("true", StringComparison.CurrentCultureIgnoreCase))
                {
                    // updates the current user details and stores it in the session state
                    Session["Profile"] = repo.UpdateUserDetails(ShipDet, User.Identity.Name);
                }
                cspInfo.ShoppingCart = cart;
                cspInfo.ShippingDetails = ShipDet;
                Session["CartShipPayInfo"] = cspInfo; // save the whole order data class into session state
                ViewData["cartValue"] = cart.ComputeCartValue().ToString("c");

                return View(new CreditCardInfo());
            }
            else
            {
                return View("Checkout", new ShippingInfo(repo) { ShipDet = ShipDet });
            }
        }








        private void PrepareCreditCardFields()
        {
            IEnumerable<string> list = new List<string>
              {
                "month",
                "01",
                "02" ,
                "03" ,
                "04" ,
                "05" ,
                "06" ,
                "07" ,
                "08" ,
                "09" ,
                "10" ,
                "11" ,
                "12" 
              };



            IEnumerable<string> list2 = new List<string>
            {
                "year",
                "2014",
                "2015",
                "2016",
                "2017",
                "2018",
                "2019",
                "2020",
                "2021",
                "2022",
                "2023",
                "2024",
                "2025" 
        };


            ViewData["months"] = new SelectList(list, list.First());
            ViewData["years"] = new SelectList(list2, list2.First());
        }




        public ViewResult RedirectAfterCancel()
        {
            return View();
        }








        public PartialViewResult GetShipAddr(string StreetNumber, string StreetName, string StreetType,
                                                 string PostCode, string Town, string State, string Country)
        {
            AddressSearchClient client = new AddressSearchClient();
            AddressResult result = client.findAddress(StreetNumber, StreetName, StreetType, Town, PostCode, null);


            if (result.numRecs != 0)
            {
                return PartialView("_GetShipAddr", result.addresses);
            }
            else return PartialView("_GetShipAddr", result.addresses);
        }



        public ViewResult GetTermsAndConditions()
        {
            return View();
        }

        public ViewResult GetPrivacyPolicy()
        {
            return View();
        }

    }
}

WebUI2/Controllers/FooterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI2.Controllers
{
    public class FooterController : Controller
    {

        public  PartialViewResult FooterContent()
        {

            return PartialView();
        }
	}
}

WebUI2/Controllers/NavigatorController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI2.Models;

namespace WebUI2.Controllers
{

    /// <summary>
    /// Provides logic for navigation based on the category of the product required by the user
    /// </summary>
    public class NavigatorController : Controller
    {
        IRepository repo;
        public NavigatorController(IRepository repo)
        {
            this.repo = repo;
        }

        public PartialViewResult Menu(string currentCategory = null)
        {
            ViewBag.CurrentCategory = currentCategory;
            List<CategoryInfo> catModels = new List<CategoryInfo>();
            IEnumerable<string> categories = repo.Products
                                             .Select(x => x.Category)
                                             .Distinct()
                                             .OrderBy(x => x);

            foreach (var cat in categories)
            {
                catModels.Add(new CategoryInfo { Name = cat, SubCategories = new List<string>() });
            }


            foreach (var product in repo.Products)
            {
                foreach (var catModel in catModels)
                {
                    if (product.Category == catModel.Name)
                    {
                        catModel.SubCategories.Add(product.SubCategory);
                    }
                    catModel.SubCategories = catModel.SubCategories.Distinct().ToList();
                }

            }

            return PartialView(catModels);
        }
    }
}

WebUI2/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using WebUI2.Models;
using System.Configuration;
using System.Data.SqlClient;
using WebUI2.Binders;
using Model.Entities;
using Model.ExternalAuthentication;
using System.Threading.Tasks;
using Model.EF;
using System.Net.Http;
using System.Net;
using System.Web.Helpers;
using Newtonsoft.Json.Linq;
using System.Collections;





namespace WebUI2.Controllers
{


    /// <summary>
    /// Contains business logic necessary to display, update and manage products information to the user.
    /// Also processes products search requests
    /// </summary>
    public class ProductsController : Controller
    {
        private IRepository repository;
        public int pageSize = 4;


        public ProductsController(IRepository repository)
        {
            this.repository = repository;
        }



        /// <summary>
        /// retrieves products data from the database and sends all necessary info for display to the view
        /// </summary>
        public ViewResult List(string currentCategory, string currentSubCategory)
        {
            IQueryable<Product> products = (repository.Products)
                                 .Where(p => currentCategory == null || p.Category == currentCategory)
                                 .Where(p => currentSubCategory == null || p.SubCategory == currentSubCategory)
                                 .OrderBy(p => p.ProductID)
                                 .Take(pageSize);

            PagingInfo info = new PagingInfo
            {
                Products = (IEnumerable<Product>)products,
                PageSize = pageSize,
                Category = currentCategory,
                SubCategory = currentSubCategory
            };
            return View(info);
        }








        public ActionResult AjaxList(string currentCategory, string subCategory, int skipSize, int addSize = 0)
        {
            IQueryable<Product> products = (repository.Products)
                                 .Where(p => currentCategory == "" || p.Category == currentCategory)
                                 .Where(p => subCategory == "" || p.SubCategory == subCategory)
                                 .OrderBy(p => p.ProductID)
                                 .Skip(skipSize)
                                 .Take(addSize);



            return PartialView("_ProductsBundle", products);
        }





        public FileContentResult GetImage(int productId)
        {
            Product product = repository.Products.First(p => p.ProductID == productId);
            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }



        public ViewResult ShowDetailedDescription(int productId, string returnUrl)
        {
            if (returnUrl.Contains("/Products/AjaxList"))
            {
                returnUrl = "/Products/List";
            }

            ViewData["returnUrl"] = returnUrl;
            Product product = repository.Products.First(p => p.ProductID == productId);

            // create an instance of the recently viewed class  - to store the products viewed
            RecentlyViewed recentViews =
                (RecentlyViewed)(new RecentViewsModelBinder()).BindModel(this.ControllerContext, new ModelBindingContext());


            // make sure only one instance of each product is added to the view
            if (!recentViews.ContainsProduct(product))
            {
                recentViews.AddRecentProduct(product);
            }
            else
            {
                recentViews.AddProductAndMove(product);
            }

            IEnumerable<int> sizeIds = product.ProductToSizes.Select(p => p.SizeId);
            IEnumerable<int> colorIds = product.ProductToColors.Select(p => p.ColorId);

            ProductInfo inf = new ProductInfo {
                                                 SizeHolders = repository.
                                                 Sizes.Where(p => sizeIds.Contains(p.Id)).
                                                 Select(d => d.Value).ToArray(),
                                                 Product = product,
                                                 ColorHolders = repository.
                                                 Colors.Where(p => colorIds.Contains(p.ColorId)).
                                                 Select(d => d.Value).ToArray()
                                              };
            return View(inf);
        }





        public ActionResult SearchDatabase(string searchWord)
        {
            SearchData data = new SearchData();
            data.Results = repository.GetSearchResults(searchWord);
            return PartialView("_SearchResults", data.Results);
        }



        [HttpGet]
        public JsonResult AddFavourite(int productId)
        {
            ApplicationUser user = (ApplicationUser)Session["Profile"];


            if (repository.AddFavourite(user.UserName, productId))
            {
                Session["Profile"] = repository.FindByName(user.UserName);
                var jsonData = new AddFavModel { Result = "success", UserName = user.UserName };
                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var jsonData = new AddFavModel { Result = "fail", UserName = user.UserName };
                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
        }//


        public ViewResult WishList(string UserName, string returnUrl = "/Products/List") 
        {  
           ApplicationUser user = repository.FindByName(UserName);
           IEnumerable<FavouriteItem> wishList = user.FavouritesList.Select(p => p);
           ViewBag.Data = returnUrl; 
           return View(wishList);
        }


        [HttpGet]
        public PartialViewResult GetWishListString()
        {
            ApplicationUser user = (ApplicationUser)Session["Profile"];
            IEnumerable<FavouriteItem> wishList = user.FavouritesList.Select(p => p);
            ViewBag.returnUrl = "/Account/Personal";
     
            return PartialView("_WishListInner", wishList);
        }



        public ViewResult DeleteFromWishList(string userName, int productId) 
        {
            repository.RemoveFavourite(userName, productId);
            IEnumerable<FavouriteItem> wishList = repository.FindByName(userName).FavouritesList.Select(p => p);
            Session["Profile"] = repository.FindByName(userName);
            ViewBag.Data = "/Products/List";
            return View("WishList", wishList);
        }


        public String GetProdName(int productId) 
        {
            return repository.Products.Where(p => p.ProductID == productId).First().Name;
        }

    }
}

WebUI2/Views/Shared/ConfirmPayment.cshtml
@model Model.EF.Order




<script>

   function getReceipt(id) {
       window.open("/Home/PrintReceipt?id=" + id, null, null, true);
   }
</script>




    <h3>
    <br />
    Thank you for your order. Your transaction has been completed and a receipt for your purchase has been mailed to you.
    <br />
    <br />

</h3>




        <div>
            Following are the details of this transaction
            <div style="float:right">
                <input type="submit" value="Print Receipt" onclick="return getReceipt(@Model.Id)" />
            </div>
        </div>
        <br />
        <br />
   




    <div class="transSummary">
        <table>


            <tr>
                <td>
                    Buyer Name
                </td>
                <td>
                    @Model.ShiptoName
                </td>
            </tr>

            <tr>
                <td>
                    Payment Amount
                </td>
                <td>
                    @Model.Total
                </td>
            </tr>

            <tr>
                <td>
                    Transaction ID
                </td>
                <td>
                    @Model.RequestTxnId
                </td>
            </tr>

            <tr>
                <td>
                    Buyer's Contact Number
                </td>
                <td>
                    @Model.CspContactNumber
                </td>
            </tr>
            <tr>
                <td>
                    Shipping Address
                </td>
                <td>
                    @Model.CspShippingAddress
                </td>
            </tr>

            <tr>
                <td>
                    Purchased Products
                </td>
                <td>
                    @Model.RequestListOfProducts
                </td>
            </tr>
        </table>
    </div>

WebUI2/Views/Shared/ProductDetails.cshtml
@model Model.EF.Product






<div class="product">


    <table>
        <tr>
            <td valign="top">
                <a id="@Model.ProductID"
                    href="/Products/ShowDetailedDescription?productId=@Model.ProductID&returnUrl=@Request.Url.PathAndQuery"
                   class="details-link">
                   
                     <img class="product-image"
                         src="@Url.Action("GetImage", "Products", new { productId = Model.ProductID})" />
                </a>


                <div style="height:60px; margin-top:10px;">
                    <input type="submit" class="add-to-cart" style="width:80%;" id="@Model.ProductID" value="Add to Cart" />
                    @{
                        string str = Model.ProductID + "loading-image";
                        <img id="@str" class="spinner" src="~/Content/MyImages/spinner.gif" />
                    }
                </div>

            </td>

            <td style="width:35%;" valign="top">
                @{
                    string id = Model.ProductID + "product-image-pop";
                    <img id="@id" class="product-image-pop" src="@Url.Action("GetImage", "Products", new { productId = Model.ProductID})" />
                }

                <h3>@Model.Name</h3>

                <a class="more-detail-link" href="~/Products/ShowDetailedDescription?productId=@Model.ProductID&returnUrl=@Request.Url.PathAndQuery"> read more...</a>
                <h4>@Model.Price.ToString("c")</h4>



                @if (Session["Profile"] != null)
                {
                    Model.ExternalAuthentication.ApplicationUser user =
                                           (Model.ExternalAuthentication.ApplicationUser)Session["Profile"];
                    if ((user.FavouritesList.Where(p => Convert.ToInt32(p.ProductID) == Model.ProductID)).Count() == 0)
                    {
                        string divId = Model.ProductID + "link";
                       <div class="add-to-fav" id="@divId">
                          <input type="hidden" id="@Model.ProductID" />
                          Add To Wish List
                      </div>
                    }
                    else 
                    { 
                        
                      <a class="more-detail-link" href="/Products/WishList?UserName=@user.UserName&returnUrl=/Products/List">view my wish list</a>
                    }
                }
            </td>
        </tr>
    </table>



</div>

WebUI2/Views/Shared/_AdminLayout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html>
<head>
    <title></title>
    @*<link href="~/Content/AdminCSS.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>*@
</head>
<body>

<div id="header">

    <div class="title">
        @using (Html.BeginForm("Home", "Home"))
        {
            <input class="logo-button" type="image" src="~/Content/MyImages/haze.png"/>

            @Html.ActionLink("Home", "Home", "Home")
            @Html.ActionLink("About Us", "AboutUs", "Home")
            @Html.ActionLink("Contact Us", "ContactUs", "Home")
            @Html.ActionLink("Testimonials", "Testimonials", "Home")
        }
    </div>
</div>
<div class="body">
    @if (TempData["Confirmation"] != null)
    {
        <div class="confirm-green">@TempData["Confirmation"]</div>
    }
    else if (TempData["Fail"] != null)
    {
        <div class="fail-red">@TempData["Fail"]</div>
    }

    @RenderBody()
</div>
</body>

   @Scripts.Render("~/bundles/adminScripts")
   @Styles.Render("~/bundles/adminStyles")

</html>

WebUI2/Views/Shared/_ErrorDisplay.cshtml
 

<img src="~/Content/MyImages/error.jpg" style="max-width:100px;margin-top:20px" />

WebUI2/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <title>Welcome! | Stesha</title>
    @Scripts.Render("~/bundles/scripts")
    @Styles.Render("~/bundles/styles")
</head>


<body>
    <div id="header">
        <table style="width:100%;">
            <tr>
                <td>
                    <div class="title">

                        @using (Html.BeginForm("Home", "Home"))
                        {
                            <input class="logo-button" type="image" src="~/Content/MyImages/haze.png" />

                            @Html.ActionLink("Home", "Home", "Home")
                            @Html.ActionLink("About Us", "AboutUs", "Home")
                            @Html.ActionLink("Contact Us", "ContactUs", "Home")
                            @Html.ActionLink("Buy", "List", "Products")
                        }

                    </div>
                </td>
                <td>

                    <div class="member-console">
                        @{
                            if (Session["Profile"] == null)
                            {

                                @Html.ActionLink("Log in", "Login", "Account")
                                //&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                @Html.ActionLink("Register", "Register", "Account")
                            }

                            else
                            {
                                Model.ExternalAuthentication.ApplicationUser cust = (Model.ExternalAuthentication.ApplicationUser)Session["Profile"];

                                @Html.ActionLink("Sign Off", "Signoff", "Account")
                                @Html.ActionLink("Logged in as " + cust.UserName, "Personal", "Account", null, null)

                            }
                        }

                    </div>
                </td>
            </tr>
            <tr>
                <td></td>

                <td>
                    @{
                        Html.RenderAction("CartSummary", "Cart");
                    }
                </td>
            </tr>
        </table>
    </div>


    <table style=" width:95%; margin-left:10px; margin-right:10px;">
        <tr>
            <td style="vertical-align:top;">


                @Html.Action("Menu", "Navigator")


            </td>
            <td>

                <div id="content">
                    @if (TempData["Confirm"] != null)
                    {
                        <div class="confirm-green">@TempData["Confirm"]</div>
                    }
                    else if (TempData["Fail"] != null)
                    {
                        <div class="fail-red">@TempData["Fail"]</div>
                    }

                    @RenderBody()




                    @{

                        Html.RenderAction("ViewsSummary", "Home");
                    }


                </div>
            </td>
        </tr>
    </table>

    @{
        Html.RenderAction("FooterContent", "Footer");
    }

</body>
</html>

WebUI2/Views/Shared/_PopupDialog.cshtml
<style>
    .web_dialog_overlay {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
        background: #000000;
        opacity: .6;
        filter: alpha(opacity=15);
        z-index: 101;
        display: none;
    }

    .web_dialog {
        border-radius: 13px;
        border-width: 5px;
        display: none;
        position: fixed;
        width: 400px;
        height: 240px;
        top: 50%;
        left: 50%;
        margin-left: -190px;
        margin-top: -100px;
        background-color: #357665;
        border: 2px solid #336699;
        padding: 0;
        z-index: 102;
        font-family: Verdana;
        font-size: 10pt;
    }

    .web_dialog_title {
        border-bottom: solid 2px #336699;
        background-color: #286c5a;
        padding: 4px;
        font-weight: bold;
    }

        .web_dialog_title a {
            color: White;
            text-decoration: none;
        }

    .align_right {
        text-align: right;
    }

    .dialog-button {
        width: 180px;
        height: 50px;
    }
</style>




<div id="overlay" class="web_dialog_overlay"></div>

<div id="dialog" class="web_dialog">
    <table style="width: 100%; margin-top:10%; border: 0;" cellpadding="3" cellspacing="0">

        <tr style="font-size:14pt; padding:5px;">
            <td style="font-size: 14pt; text-align: center; ">@ViewData["message"]</td>
        </tr>

        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center;">
                <input class="dialog-button" id="confirm" type="button" value="yes" />
                <input class="dialog-button" id="decline" type="button" value="no" />
            </td>
        </tr>
    </table>
</div>

WebUI2/Views/Shared/_ProductsBundle.cshtml
@model IEnumerable<Model.EF.Product>







@if (Model.Count() != 0)
{

    <table>
        @for (int i = 0; (i + 1) < Model.Count(); i += 2)
        {

            @:<tr>


                @:<td valign="top" width="50%">




            Html.RenderPartial("ProductDetails", Model.ElementAt(i));


            @:</td>


            @:<td valign="top" width="50%">




            Html.RenderPartial("ProductDetails", Model.ElementAt(i + 1));


            @:</td>


            @:</tr>
        }
    </table>
}

else
{
    @:0
}

WebUI2/Views/Shared/_StoreFrontLayout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html>
<head>
    <title>Welcome! | Stesha</title>
    @Scripts.Render("~/bundles/scripts")
    @Styles.Render("~/bundles/styles")
</head>




<body>
    <div id="header">
        <table style="width:100%;">
            <tr>
                <td>
                    <div class="title">

                        @using (Html.BeginForm("Home", "Home"))
                        {
                            <input class="logo-button" type="image" src="~/Content/MyImages/haze.png" />
                            @Html.ActionLink("Home", "Home", "Home")
                            @Html.ActionLink("About Us", "AboutUs", "Home")
                            @Html.ActionLink("Contact Us", "ContactUs", "Home")
                            @Html.ActionLink("Buy", "List", "Products")
                        }

                    </div>
                </td>



                <td>
                    <div class="member-console">
                        @{
                            if (Session["Profile"] == null)
                            {

                                @Html.ActionLink("Log in", "Login", "Account")
                                @Html.ActionLink("Register", "Register", "Account")
                            }

                            else
                            {
                                var cust = (Model.ExternalAuthentication.ApplicationUser)Session["Profile"];

                                @Html.ActionLink("Sign Off", "Signoff", "Account")
                                @Html.ActionLink("Logged in as " + cust.UserName, "Personal", "Account")
                            }
                        }

                    </div>
                </td>
            </tr>
            <tr>

                <td></td>
                <td>
                    @{
                        Html.RenderAction("CartSummary", "Cart");
                    }
                </td>
            </tr>
        </table>
    </div>


    @RenderBody()

</body>
</html>