WebUI2/Controllers/CartController.cs
using Model;
using Model.Abstracts;
using Model.EF;
using Model.Entities;
using Model.ExternalAuthentication;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebUI2.Models;
using WebUI2.SearchAddress;




namespace WebUI2.Controllers
{

    /// <summary>
    /// Processes all user actions related to their cart and items placed in the cart.
    /// Prepares data necessary for checkout and performs address and model validation
    /// </summary>
    public class CartController : Controller
    {
        IRepository repo;
        IPaymentProcessor paymentProcessor;
        IMailProcessor mailSender;



        public CartController(IRepository repo, IPaymentProcessor paymentProcessor, IMailProcessor mailSender)
        {
            this.repo = repo;
            this.paymentProcessor = paymentProcessor;
            this.mailSender = mailSender;
        }




        // we get the cart object from the cartModelBinder
        public String AddItemAjax(ShoppingCart cart, int productId, string returnUrl, string returnUrl2, string size, string color)
        {
            Product product = repo.Products.FirstOrDefault(p => p.ProductID == productId);
            product.SelectedSize =( size ?? repo.Sizes.First().Value);
            product.SelectedColour = (color ?? repo.Colors.First().Value);
            cart.AddItem(product);
            string str = "Your Cart:  " + cart.ProductLines.Sum(x => x.Quantity) + " item(s): " +
            cart.ComputeCartValue().ToString("c");

            return str;
        }




        public RedirectResult AddItem(ShoppingCart cart, int productId, string returnUrl, string returnUrl2)
        {
            Product product = repo.Products.Where(p => p.ProductID == productId).FirstOrDefault();
            cart.AddItem(product);

            if (returnUrl != null)
            { return Redirect(returnUrl); }

            else
            { return Redirect(returnUrl2); }
        }



        public RedirectToRouteResult RemoveItem(ShoppingCart cart, int productId, string returnUrl)
        {
            Product product = repo.Products.Where(p => p.ProductID == productId).FirstOrDefault();
            cart.RemoveItem(product);

            return RedirectToAction("Index", new { returnUrl });
        }


        public ViewResult Index(ShoppingCart cart, string returnUrl)
        {
            CartInfo cartInfo = new CartInfo();
            cartInfo.Cart = cart;
            cartInfo.ReturnUrl = returnUrl;
            return View(cartInfo);
        }

        public PartialViewResult CartSummary(ShoppingCart cart)
        {
            return PartialView(cart);
        }





        public ViewResult Checkout(ShoppingCart cart)
        {
            string countryName = RegionInfo.CurrentRegion.DisplayName;

            if (cart.ProductLines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your cart is empty");
            }

            if (ModelState.IsValid)
            {
                // this message will be used by popup dialog window
                ViewData["message"] = "Would you like to update your details?";
                // user is logged in - use their details
                if (Session["Profile"] != null)
                {
                    // initialize objects to be passed to the view
                    ShippingInfo shipInfo = InitializeModel(repo);
                    return View(shipInfo);
                }
                else
                {   // if the user is not registered return a blank class
                    return View(new ShippingInfo(repo) { ShipDet = new ShippingDetails { Country = countryName } });
                }
                

            }
            else
            {
                CartInfo inf = new CartInfo
                {
                    Cart = cart,
                    ReturnUrl = "/"
                };
                return View("Index", inf);
            }
        }





        private ShippingInfo InitializeModel(IRepository repo)
        {

            ApplicationUser prof = (ApplicationUser)Session["Profile"];

            ShippingInfo shipInfo = new ShippingInfo(repo)
            {
                ShipDet = new ShippingDetails()
                {
                    Name = prof.Name,
                    Surname = prof.Surname,
                    Email = prof.Email,
                    Phone = prof.Phone
                }
            };


            if (prof.ShippingAddressId != null)
            {
                ShippingAddress adr = prof.ShippingAddress.Where(p => p.RecordId == prof.ShippingAddressId).First();
                // if address data is present fill the model

                shipInfo.ShipDet.UnitFlat = adr.UnitNumber;
                shipInfo.ShipDet.Town = adr.Town;
                shipInfo.ShipDet.StreetType = adr.StreetType;
                shipInfo.ShipDet.StreetNumber = adr.StreetNumber;
                shipInfo.ShipDet.StreetName = adr.StreetName;
                shipInfo.ShipDet.State = adr.State;
                shipInfo.ShipDet.PostCode = adr.PostCode;
                shipInfo.ShipDet.Country = adr.Country;
            }

            return shipInfo;
        }





        [HttpPost]
        public ViewResult ProceedToPay(ShoppingCart cart, ShippingDetails ShipDet, string updateUser)
        {
            
            if (ModelState.IsValid)
            {
                CartShipPayInfo cspInfo = new CartShipPayInfo();
                // prepare for credit card payment
                PrepareCreditCardFields();

                if (updateUser == null ? false : updateUser.Equals("true", StringComparison.CurrentCultureIgnoreCase))
                {
                    // updates the current user details and stores it in the session state
                    Session["Profile"] = repo.UpdateUserDetails(ShipDet, User.Identity.Name);
                }
                cspInfo.ShoppingCart = cart;
                cspInfo.ShippingDetails = ShipDet;
                Session["CartShipPayInfo"] = cspInfo; // save the whole order data class into session state
                ViewData["cartValue"] = cart.ComputeCartValue().ToString("c");

                return View(new CreditCardInfo());
            }
            else
            {
                return View("Checkout", new ShippingInfo(repo) { ShipDet = ShipDet });
            }
        }








        private void PrepareCreditCardFields()
        {
            IEnumerable<string> list = new List<string>
              {
                "month",
                "01",
                "02" ,
                "03" ,
                "04" ,
                "05" ,
                "06" ,
                "07" ,
                "08" ,
                "09" ,
                "10" ,
                "11" ,
                "12" 
              };



            IEnumerable<string> list2 = new List<string>
            {
                "year",
                "2014",
                "2015",
                "2016",
                "2017",
                "2018",
                "2019",
                "2020",
                "2021",
                "2022",
                "2023",
                "2024",
                "2025" 
        };


            ViewData["months"] = new SelectList(list, list.First());
            ViewData["years"] = new SelectList(list2, list2.First());
        }




        public ViewResult RedirectAfterCancel()
        {
            return View();
        }








        public PartialViewResult GetShipAddr(string StreetNumber, string StreetName, string StreetType,
                                                 string PostCode, string Town, string State, string Country)
        {
            AddressSearchClient client = new AddressSearchClient();
            AddressResult result = client.findAddress(StreetNumber, StreetName, StreetType, Town, PostCode, null);


            if (result.numRecs != 0)
            {
                return PartialView("_GetShipAddr", result.addresses);
            }
            else return PartialView("_GetShipAddr", result.addresses);
        }



        public ViewResult GetTermsAndConditions()
        {
            return View();
        }

        public ViewResult GetPrivacyPolicy()
        {
            return View();
        }

    }
}

WebUI2/Controllers/PayFlowDirectController.cs
using Model;
using Model.EF;
using Model.Entities;
using Model.ExternalAuthentication;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.CompilerServices;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebUI2.Models;

namespace WebUI2.Controllers
{

    /// <summary>
    /// Prepares a credit card payment reuest to be sent to the PayPal's PayFlow payment gateway.
    /// Verifies the response received from the PayPal server and stores order information in the database
    /// </summary>
    public class PayFlowDirectController : Controller
    {
      IRepository repo;
     

       public PayFlowDirectController(IRepository repo)
       {
          this.repo = repo;
       }



        // use following test details for FDMS Nashvillle processor 4111111111111111 (a 4 and fifteen 1’s), expiration date 12/15, card security code 123.




        public ActionResult Set(CreditCardInfo card)
        {
            CartShipPayInfo csp = (CartShipPayInfo)Session["CartShipPayInfo"];
            PayFlowRequest req = SetReq(csp, card);

            string payLoad = req.BuildPayload();        
            string response = SendReq(req.Endpoint, payLoad, BuildHeaders());
            string result = GetValue(response, "RESULT");
            Order order = CopyDirectPaymentToOrder(response);

           if (result.Equals("0") && GetValue(response,"CVV2MATCH") == "Y")
            {
                TempData["Confirm"] = "The payment has been successfully processed";
                
                repo.SaveAllToDatabase(order);
                csp.ShoppingCart.ClearCart();

                return View("ConfirmPayment", order);
            }
            else 
            {
                TempData["Fail"] = "Payment failed";
                repo.SaveIncompleteOrder(order);
                return View("_ErrorDisplay");
            }
     

       }

        private PayFlowRequest SetReq(CartShipPayInfo csp, CreditCardInfo card)
        { 
            PayFlowRequest req = new PayFlowRequest
            {
                Pwd = "1812war347813",
                Vendor = "stesha",
                User = "stesha",
                Partner = "VSA",//id of the gateway provider
                //live endpoint
                // Endpoint = "https://payflowpro.paypal.com",
                //test endpoint
                Endpoint = "https://pilot-payflowpro.paypal.com",
                Amt = Convert.ToString(csp.ShoppingCart.ComputeCartValue()), // amount of sale with two decimal places
                Currency = "AUD",
                Trxtype = "S",                  // type of transaction S-for sale
                Tender = "C",                   // method of payment C - for credit card
                Timeout = "300",
                Verbosity = "HIGH",
                Hostport = "443",
               
                // temp values
                SecCode = card.Verification,
                Acct = card.Account,           // creit card number
                ExpDate = "0719"//card.months + card.years

                ///additional possible settings
                ///SILENTTRAN=TRUE // for silent redirect
            };

            return req;
        }






          private NameValueCollection BuildHeaders()
           {
              string uniqueId = genId();
              
              NameValueCollection col = new NameValueCollection()
               {
                  {"X-VPS-REQUEST-ID", uniqueId},// id used to verify transaction is not duplicate (page 157, PayFlow Gateway Deveoper guide) 
                  {"X-VPS-CLIENT-TIMEOUT", "400"}              
               };      
       
               return col;
           }





      public string SendReq(string endpoint, string payLoad, NameValueCollection headers)
        {
            // Create the request
            HttpWebRequest request =
                  (HttpWebRequest)WebRequest.Create(endpoint);
            // Set values for the request
        
            request.Method = "POST";
            request.ContentType = "text/name value";
            request.ContentLength = payLoad.Length;
            request.Headers.Add(headers);

            // Write the request
            StreamWriter writer =
            new StreamWriter(request.GetRequestStream());
            writer.Write(payLoad);
            writer.Close();

            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            Stream responseStream = response.GetResponseStream();
            Encoding encoding = Encoding.GetEncoding("utf-8");
            StreamReader reader = new StreamReader(responseStream, encoding);
            string responseStr = "";

            while (!reader.EndOfStream)
            {
                responseStr += reader.ReadLine();
            }

            return responseStr;
        }



    
        // generates a random unique ID for use in the initial CREATESECURETOKEN=Y request
        protected string genId()
        {
            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            var random = new Random();
            var result = new string(
                Enumerable.Repeat(chars, 16)
                          .Select(s => s[random.Next(s.Length)])
                          .ToArray());
            return "MySecTokenID-" + result; //add a prefix to avoid confusion with the "SECURETOKEN"
        }

    




    private string GetValue(string p, string key)
        {
            p = Convert.ToString(HttpUtility.UrlDecode(p));

            string[] delimiters = { "=", "&" };
            string[] words = p.Split(delimiters, StringSplitOptions.RemoveEmptyEntries);

            for (int i = 0; i < words.Length; i++)
            {
                if (words[i].Equals(key))
                    return words[i + 1];
            }

            return null;
        }





        private Order CopyDirectPaymentToOrder(string resp)
        {
           CartShipPayInfo csp = (CartShipPayInfo)Session["CartShipPayInfo"];
           string customerId = (Session["Profile"] == null) ? csp.ShippingDetails.Email : 
                                                    Convert.ToString(((ApplicationUser)Session["Profile"]).Id);          

            Order order = new Order
            {
                CspPayerEmail = csp.ShippingDetails.Email,
                CspShippingAddress = csp.ShippingDetails.GetAddress(),
                RequestCurrency = GetValue(resp, "CURRENCY"),
                RequestFirstName = csp.ShippingDetails.Name,
                RequestLastName = csp.ShippingDetails.Surname,
                Total = csp.ShoppingCart.ComputeCartValue().ToString("c"),
                RequestPayerId = customerId,
                RequestTxnType = "Sale",
                RequestReceiverId = "Stesha Pty Ltd",
                RequestListOfProducts = csp.ShoppingCart.GetProductsList(),
                RequestPaymentDate = GetValue(resp, "TRANSTIME") == null ? DateTime.Now.ToString() : GetValue(resp, "TRANSTIME"),
                CspContactNumber = ((csp.ShippingDetails.Phone == null) ? "not provided" : csp.ShippingDetails.Phone),
                CartNumberOfItems = Convert.ToString(csp.ShoppingCart.ProductLines.Sum(p => p.Quantity)),
                RequestPaymentStatus = GetValue(resp, "RESPMSG"),
                RequestTxnId = GetValue(resp, "PNREF"),
            };


            return order;
        }
	





    
    }
}




    

WebUI2/Views/Cart/CartSummary.cshtml
@model Model.Entities.ShoppingCart





<div class="check-out-button">
    @Html.ActionLink("Checkout", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, null)

    @{
        string str = "Your Cart:  " + Model.ProductLines.Sum(x => x.Quantity) + " item(s): " +
        Model.ComputeCartValue().ToString("c");


        @Html.ActionLink(str, "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, new { id="cart-values"})

    }
</div>

WebUI2/Views/Cart/Checkout.cshtml
@model WebUI2.Models.ShippingInfo

@*<script src="~/Scripts/ShippingFormScripts.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@


<script type="text/javascript">
    function openNew(id) {
        if (id == "privacy") {
            window.open("/Cart/GetPrivacyPolicy", "name", null, true);
        }
        else {
            window.open("/Cart/GetTermsAndConditions", "name", null, true);
        }
    }

</script>


<script>

    function detailsChanged() {
        if ($("#ShipDet_Name").val() != $("#OldName").val()) return true;
        if ($("#ShipDet_Surname").val() != $("#OldSurname").val()) return true;
        if ($("#ShipDet_StreetNumber").val() != $("#OldStreetNumber").val()) return true;
        if ($("#ShipDet_StreetName").val() != $("#OldStreetName").val()) return true;
        if ($("#ShipDet_StreetType").val() != $("#OldStreetType").val()) return true;
        if ($("#ShipDet_Town").val() != $("#OldTown").val()) return true;
        if ($("#ShipDet_State").val() != $("#OldState").val()) return true;
        if ($("#ShipDet_PostCode").val() != $("#OldPostCode").val()) return true;
        if ($("#ShipDet_Country").val() != $("#OldCountry").val()) return true;
        if ($("#ShipDet_Email").val() != $("#OldEmail").val()) return true;
        if ($("#ShipDet_Phone").val() != $("#OldPhone").val()) return true;

        return false;
    }





    function noEmptyFields() {
        if (
            $("#ShipDet_Name").val() == '' ||
            $("#ShipDet_Surname").val() == '' ||
            $("#ShipDet_StreetNumber").val() == ''||
            $("#ShipDet_StreetName").val() == '' ||
            $("#ShipDet_Town").val() == '' ||
            $("#ShipDet_State").val() == '' ||
            $("#ShipDet_PostCode").val() == '' ||
            $("#ShipDet_Email").val() == '' ||
            $("#ShipDet_Phone").val() == ''
            ) return false;

        return true;
    }





    $(document).ready(function () {


        $("#submitButton").click(function (e) {


            if ($("#member").val() == "true") {
                if (noEmptyFields()) {
                    if (detailsChanged()) {
                        ShowDialog(true);
                        e.preventDefault();
                    }
                }
            }
        });





        $("#confirm").click(function (e) {

            $("#updateUser").val("true");
            $("#shipmentForm").submit();
            HideDialog();


        });


        $("#decline").click(function (e) {

            $("#updateUser").val("false");
            $("#shipmentForm").submit();
            HideDialog();
        });
    });



    function ShowDialog() {

        $("#overlay").show();
        $("#dialog").fadeIn(300);
        $("overlay").unbind("click");
    }

    function HideDialog() {

        $("#overlay").hide();
        $("#dialog").fadeOut(300);
    }

</script>






<h2>Please enter your shipping details below</h2>
(fields marked with (*) are required)
<hr />

@using (Html.BeginForm("ProceedToPay", "Cart", Model.ShipDet, FormMethod.Post,
    new { defaultbutton = "submitButton", id = "shipmentForm" }))
{
    <div class="validation-fail">
        @Html.ValidationSummary(false)
    </div>

    <div class="editor-long" id="editor-long">
        @Html.Label("Name *")
        @Html.EditorFor(x => x.ShipDet.Name)
        <br />

        @Html.Label("Family name *")
        @Html.EditorFor(x => x.ShipDet.Surname)
        <br />
        <br />
        <hr />
        
        <h3>Address</h3>
        
        <br />
        <br />
        @Html.Label("Country *")
        @Html.DropDownListFor(x => x.ShipDet.Country, new SelectList(Model.CountriesSelectList,
                                                                "Name", "Name", Model.CountriesSelectList.First()))
        <br />
        @Html.Label("State *")
        @Html.EditorFor(x => x.ShipDet.State)



        <br />
        @Html.Label("Unit/Flat Number")
        @Html.EditorFor(x => x.ShipDet.UnitFlat)
        <br />

        @Html.Label("Street Number *")
        @Html.EditorFor(x => x.ShipDet.StreetNumber)
        <br />





        @Html.Label("Street Name *")
        @Html.EditorFor(x => x.ShipDet.StreetName)


        <br />

        @Html.Label("Street Type *")
        @Html.DropDownListFor(p => p.ShipDet.StreetType,
                        new SelectList(Model.StreetTypeSelectData, Model.StreetTypeSelectData.First()))

        <br />

        @Html.Label("Town *")
        @Html.EditorFor(x => x.ShipDet.Town)


        <br />
        @Html.Label("Postcode *")
        @Html.EditorFor(x => x.ShipDet.PostCode)
        <br />

        <div id="auto-complete-div">
            <div id="status" class="status">
            </div>

            <div>
                <img style="width:30px; display:none;" id="address-loading" src="~/Content/MyImages/spinner.gif" />
            </div>
            <br />
            
            <div id="addr-records">

            </div>
        </div>


        <hr />
        <h3>Contact Details</h3>


        @Html.Label("Email Address *")
        @Html.EditorFor(x => x.ShipDet.Email)
        <br />

        @Html.Label("Phone *")
        @Html.EditorFor(x => x.ShipDet.Phone)
    </div>
    <br />


    <hr />
    <p class="actionButton" align="center">
        <input type="submit" id="submitButton" value="Proceed to payment" />
    </p>


    @: By placing your order you agree to the 
    <a id="conditions" style="cursor:pointer" onclick="return openNew(this.id)">terms and conditions</a> 
    @:and
    <a id="privacy" style="cursor:pointer" onclick="return openNew(this.id)"> privacy policy" </a> 
    @: of Stesha Pty Ltd (ABN 19 731 703 340)

    
    if (Model.ShipDet.Email != null)
    {
        @Html.Hidden("member", "true")
        @Html.Hidden("updateUser", "false")
        @Html.Hidden("OldName", Model.ShipDet.Name)
        @Html.Hidden("OldSurname", Model.ShipDet.Surname)
        @Html.Hidden("OldStreetNumber", Model.ShipDet.StreetNumber)
        @Html.Hidden("OldStreetName", Model.ShipDet.StreetName)
        @Html.Hidden("OldStreetType", Model.ShipDet.StreetType)
        @Html.Hidden("OldTown", Model.ShipDet.Town)
        @Html.Hidden("OldState", Model.ShipDet.State)
        @Html.Hidden("OldPostCode", Model.ShipDet.PostCode)
        @Html.Hidden("OldCountry", Model.ShipDet.Country)
        @Html.Hidden("OldPhone", Model.ShipDet.Phone)
        @Html.Hidden("OldEmail", Model.ShipDet.Email)
        Html.RenderPartial("_PopupDialog");
    }
    else
    {
        @Html.Hidden("member", "false")
        @Html.Hidden("updateUser", "false")
    }

}

WebUI2/Views/Cart/Index.cshtml
@model WebUI2.Models.CartInfo



<h2>Your cart</h2>

<div class="validation-fail">
    @Html.ValidationSummary()
</div>

<hr />
<table width="700" align="center">
    <thead>
        <tr>
            <th align="center">Quantity</th>
            <th align="left">Item</th>
            <th align="right">Price</th>
            <th align="right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.ProductLines)
        {
            <tr>
                <td align="center">@line.Quantity</td>
                <td align="left">@line.Products.First().Name</td>
                <td align="right">@line.Products.First().Price.ToString("c")</td>
                <td align="right">@((line.Products.First().Price * line.Quantity).ToString("c"))</td>

                <td align="right">
                    @using (Html.BeginForm("RemoveItem", "Cart"))
                    {
                        @Html.Hidden("ProductID", line.Products.First().ProductID)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="actionButton" type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">Total:</td>
            <td align="right">@(Model.Cart.ComputeCartValue().ToString("c"))</td>
        </tr>
    </tfoot>
</table>



<p class="actionButton">
    <a href="@Model.ReturnUrl">Continue Shopping</a>
    @Html.ActionLink("Checkout now", "Checkout")
</p>

WebUI2/Views/Cart/ProceedToPay.cshtml
@model WebUI2.Models.CreditCardInfo


@*<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/CardFormValidation.js"></script>
<script src="~/Scripts/PopupDialogScript.js"></script>*@

<h2>Payment</h2>

Amount for payment is @ViewData["cartValue"]


<h3>Choose preferred method of payment</h3>


<table style="width:100%">
    <tr>

        <td align="center" style="border-top: solid; border-top-color: white; min-height: 600px; vertical-align: central;">

            <br /><br />


            <p class="actionButton">
                @Html.ActionLink("Pay with PayPal", "SetExpressCheckout", "ExpressCheckout")
            </p>

            Click the 'Pay with PayPal' button above to switch to PayPal billing.
            <br />

            You will be taken to PayPal's site and then returned here upon completion of payment.

            <br />
            <br />
        </td>


    </tr>
    <tr>
        <td style="min-height:600px;vertical-align:central;">
            <img src="https://www.paypal.com/en_US/i/logo/PayPal_mark_37x23.gif" />
        </td>

    </tr>
</table>





<table style="width: 100%">


    <tr>
        <td style="vertical-align: central;">
            <hr />
            <p>
                Pay With a Credit Card
            </p>
            <img src="~/Content/MyImages/cards.gif" />


            <div class="editor">

                @using (Html.BeginForm("Set", "PayFlowDirect", Model, FormMethod.Post, new { defaultbutton = "submitButton" }))
                {
                    // For direct payment pro (using nvp) submit form to: /*"SetDirectPayment"*//*"DirectPayment"*/
                    // For direct payment pro (using SOAP) submit form to: /*"SetDirectPayment"/*, /*"DirectPaymentSoap"*/

                    <div class="validation-fail">
                        @Html.ValidationSummary(false)

                        <div style="margin-left:40px;margin-bottom: 40px;">
                            <div id="card"></div>
                            <div id="month"></div>
                            <div id="year"></div>
                        </div>

                    </div>


                    <p>
                        @Html.Label("Card Number") @Html.TextBoxFor(p => p.Account)
                    </p>


                    <p>
                        @Html.Label("CVV (card security code)") @Html.TextBoxFor(p => p.Verification)
                    </p>

                    <p class="spec-sel">
                        @Html.Label("Card Type")
                        @Html.DropDownListFor(p => p.CardType,
                                            new SelectList(new string[] { "Select", "Master", "Visa" }, "Select"))
                    </p>

                    <p class="spec-sel">
                        @Html.Label("Expiry Date")

                        @Html.DropDownListFor(p => p.months,
                               ((SelectList)ViewData["months"]))

                        @Html.DropDownListFor(p => p.years,
                              ((SelectList)ViewData["years"]))
                    </p>

                    <input type="submit" id="submitButton" value="Submit Payment" />

                }

            </div>



        </td>
    </tr>
</table>


   @{
       Html.RenderPartial("_PopupDialog");
    }

WebUI2/Views/Cart/RedirectAfterCancel.cshtml
@using Model.Entities
@model WebUI2.Models.ShippingInfo


<h2>Your payment with PayPal has been cancelled</h2>


@Html.RouteLink("Return Home", "Default", new { @class = "returnLink"})
<br />
<br />

@using (Html.BeginForm("ProceedToPay", "Cart", FormMethod.Post, null)) 
{ 
    CartShipPayInfo csp = (CartShipPayInfo)Session["CartShipPayInfo"];
    Model.ShipDet = csp.ShippingDetails;
    
    @Html.ActionLink("Use a different payment method", 
                      null,
                      null,
                      null,
                      new { @class = "returnLink" })
}

WebUI2/Views/Cart/_GetShipAddr.cshtml
@model IEnumerable<WebUI2.SearchAddress.AddressRecord>


@if (Model != null)
{


    foreach (var rec in Model)
    {
        string id = Convert.ToString(rec.objectId);
        <div id="@id" class="address-record">
            @{


                @rec.shortAddressString;
                @Html.Hidden(id + "Country", "Australia");
                @Html.Hidden(id + "State", "NSW");
                @Html.Hidden(id + "StreetNumber", rec.houseNumberString);
                @Html.Hidden(id + "StreetName", rec.roadName);
                @Html.Hidden(id + "PostCode", rec.postCode);
                @Html.Hidden(id + "Town", rec.suburbName);
                @Html.Hidden(id + "StreetType", rec.roadType);
            }
        </div>
    }


}
else
{
    @:No matching addresses found
}